print('olá,mundo')
print('eu sou a marcela')
print('e tenho 21 anos')
print('sou viciada em ler')
print('to lendo um livro MUITO BOM')
print('e amando muito')
print('enfim, é isso')
print('so to escrevendo essas abobrinhas pq o carlos pediu')
print('e to morrendo de sono e quero ir embora')
print('tchau, beijo de luz')